import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

type FormulaInput = {
  version: string;
  tarballUrl: string;
  sha256: string;
};

export function buildHomebrewFormula(input: FormulaInput): string {
  validateFormulaInput(input);

  return `# typed: false
# frozen_string_literal: true

# This file was generated by the agent-plugin release workflow. DO NOT EDIT.
class AgentPlugin < Formula
  desc "Install agent plugins through native CLIs with skills fallback"
  homepage "https://github.com/Codagent-AI/agent-plugin"
  url "${input.tarballUrl}"
  sha256 "${input.sha256}"
  version "${input.version}"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")
  end

  test do
    shell_output("#{bin}/agent-plugin --version")
  end
end
`;
}

function validateFormulaInput(input: FormulaInput): void {
  if (input.version.length === 0) {
    throw new Error('version is required');
  }
  if (!input.tarballUrl.startsWith('https://registry.npmjs.org/@codagent-ai/agent-plugin/-/')) {
    throw new Error('tarballUrl must be the npm registry tarball URL for agent-plugin');
  }
  if (
    input.tarballUrl !==
    `https://registry.npmjs.org/@codagent-ai/agent-plugin/-/agent-plugin-${input.version}.tgz`
  ) {
    throw new Error('tarballUrl must match version');
  }
  if (!/^[a-f0-9]{64}$/.test(input.sha256)) {
    throw new Error('sha256 must be a lowercase 64-character hex digest');
  }
}

async function main(): Promise<void> {
  const version = requireEnv('AGENT_PLUGIN_VERSION');
  const tarballUrl = requireEnv('AGENT_PLUGIN_TARBALL_URL');
  const sha256 = requireEnv('AGENT_PLUGIN_TARBALL_SHA256');
  const outputPath = requireEnv('HOMEBREW_FORMULA_PATH');

  const formula = buildHomebrewFormula({ version, tarballUrl, sha256 });
  await writeFile(outputPath, formula);
}

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(`${name} is required`);
  }
  return value;
}

export function isMainModule(importUrl: string, argvPath: string | undefined): boolean {
  return argvPath != null && fileURLToPath(importUrl) === path.resolve(argvPath);
}

if (isMainModule(import.meta.url, process.argv[1])) {
  await main();
}
